INSERT into CLIENT_DETAILS (ID, PRIORITY, NAME) values (1 ,1, 'TNL0001');
INSERT into CLIENT_RULES (ID, CLIENT_NAME, RULE_ORDER, RULE_IDENTIFIER, ACCOUNT, BUSINESS_LINE) values (1,'TNL0001',1,'TNL-XONTRO', '045D1', 'EQUITY');
INSERT into CLIENT_RULES (ID, CLIENT_NAME, RULE_ORDER, RULE_IDENTIFIER, ACCOUNT, BUSINESS_LINE) values (2,'TNL0001',5,'TNL-XONTRO', 'ALL', 'ALL');
INSERT into CLIENT_RULES (ID, CLIENT_NAME, RULE_ORDER, RULE_IDENTIFIER, ACCOUNT, BUSINESS_LINE) values (3,'TNL0001',2,'TNL-OGD-SUMMARY', '045D1', 'FID');
INSERT into CLIENT_RULES (ID, CLIENT_NAME, RULE_ORDER, RULE_IDENTIFIER, ACCOUNT, BUSINESS_LINE) values (4,'TNL0001',3,'TNL-NY', '046A2', 'ALL');
INSERT into CLIENT_RULES (ID, CLIENT_NAME, RULE_ORDER, RULE_IDENTIFIER, ACCOUNT, BUSINESS_LINE) values (5,'TNL0001',4,'TNL-SWIFT', 'ALL', 'EQUITY');

-----
--with Rule 1 two cofirmation going through
INSERT into CLIENT_CONFIRMATION (ID, CONFIRMATION_ID , RULE_ID , CONFIRMATION_TYPE) values (1,5, 1, 'XONTRO' );
INSERT into CLIENT_CONFIRMATION (ID, CONFIRMATION_ID , RULE_ID , CONFIRMATION_TYPE) values (2,3, 1, 'POSTAL' );

--static data for confirmations
INSERT into CONFIRMATION (ID, CONFIRMATION_TYPE, DESCRIPTION ,DELIVERY_MODES ,BUSINESS_LINES) values (1, 'SUMMARY', 'multiple trade', 'Fax/email/File', 'EQUITY,FID');
INSERT into CONFIRMATION (ID, CONFIRMATION_TYPE, DESCRIPTION ,DELIVERY_MODES ,BUSINESS_LINES) values (2, 'DOCUMENT', 'Single page doc', 'Fax/email/File', 'EQUITY,FID');
INSERT into CONFIRMATION (ID, CONFIRMATION_TYPE, DESCRIPTION ,DELIVERY_MODES ,BUSINESS_LINES) values (3, 'POSTAL', 'single page doc', 'OMEGEO/DTDC', 'EQUITY');
INSERT into CONFIRMATION (ID, CONFIRMATION_TYPE, DESCRIPTION ,DELIVERY_MODES ,BUSINESS_LINES) values (4, 'CTM', 'post NY', 'post', 'EQUITY,FID');
INSERT into CONFIRMATION (ID, CONFIRMATION_TYPE, DESCRIPTION ,DELIVERY_MODES ,BUSINESS_LINES) values (5, 'XONTRO', 'rental structured', 'xontro', 'EQUITY,FID,PWN');
INSERT into CONFIRMATION (ID, CONFIRMATION_TYPE, DESCRIPTION ,DELIVERY_MODES ,BUSINESS_LINES) values (6, 'SWIFT', 'confirmation vida swift', 'swiftnet', 'EQUITY,FID,PWN');
